spring:
  config:
    import: optional:file:.env[.properties]

nexon:
  maple:
    apikey: ${API_KEY}
    id: https://open.api.nexon.com/maplestory/v1/id
    union: https://open.api.nexon.com/maplestory/v1/user
    ranking: https://open.api.nexon.com/maplestory/v1/ranking

